global class ProcessWorkitemRequest {
	global String action;
	global String workitemid;
	global ProcessWorkitemRequest() { }
	global String getAction() { }
	global String getComments() { }
	global List<Id> getNextApproverIds() { }
	global String getWorkitemId() { }
	global void setAction(String param0) { }
	global void setComments(String param0) { }
	global void setNextApproverIds(List<Id> param0) { }
	global void setWorkitemId(String param0) { }

}