global class EmailFileAttachment {
	global Blob body;
	global String contenttype;
	global String filename;
	global Id id;
	global Boolean inline;
	global EmailFileAttachment() { }
	global Blob getBody() { }
	global String getContentType() { }
	global String getFileName() { }
	global Id getId() { }
	global Boolean getInline() { }
	global void setBody(Blob param0) { }
	global void setContentType(String param0) { }
	global void setFileName(String param0) { }
	global void setInline(Boolean param0) { }

}