global class ApplicationFormInput {
	global String accountId;
	global String branchUnitId;
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global String leadId;
	global String opportunityId;
	global String recordTypeId;
	global String stage;
	global String thirdPartyLoanProviderAccountId;
	global applicationFormInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}