global class ApplicantInput {
	global String accountId;
	global String applicantPrefix;
	global String applicantSuffix;
	global String contactId;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global Datetime dateOfBirth;
	global String email;
	global String firstName;
	global Double groupExposure;
	global String lastName;
	global String middleName;
	global String phone;
	global String phoneType;
	global String recordTypeId;
	global String role;
	global String stage;
	global String uniqueReferenceNumber;
	global applicantInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}