global class CartItem {
	global String currencyIsoCode;
	global String itemizedAdjustmentAmount;
	global String listPrice;
	global String salesPrice;
	global String totalAdjustmentAmount;
	global String totalAmount;
	global String totalListPrice;
	global String totalPrice;
	global String totalTax;
	global String unitAdjustedPrice;
	global String unitAdjustmentAmount;
	global CartItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}