global class CommerceAddressOutput {
	global String addressId;
	global String addressType;
	global String city;
	global String companyName;
	global String country;
	global String countryCode;
	global Map<String,ConnectApi.RecordField> fields;
	global String firstName;
	global Boolean isDefault;
	global String lastName;
	global String middleName;
	global String name;
	global String phoneNumber;
	global String postalCode;
	global String region;
	global String regionCode;
	global String street;
	global CommerceAddressOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}