global class CommerceAddressInput {
	global String addressType;
	global String city;
	global List<ConnectApi.CommerceAddressFieldInput> commerceAddressFieldInputList;
	global String companyName;
	global String country;
	global String countryCode;
	global String firstName;
	global Boolean isDefault;
	global String lastName;
	global String middleName;
	global String name;
	global String phoneNumber;
	global String postalCode;
	global String region;
	global String regionCode;
	global String street;
	global commerceAddressInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}