global class CreateApplicationFormApplicantOutputRepresentation {
	global String applicantId;
	global List<String> partyCreditProfile;
	global List<ConnectApi.CreateAppFormPartyIdentityVerificationOutputRep> partyIdentityVerification;
	global List<String> partyProfileAddress;
	global String partyProfileId;
	global List<String> partyProfileRisk;
	global CreateApplicationFormApplicantOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}