global class EinsteinPromptTemplateGenerationsRepresentation {
	global List<ConnectApi.EinsteinLLMGenerationItemOutput> generations;
	global ConnectApi.WrappedMapObject parameters;
	global String prompt;
	global String promptTemplateDevName;
	global String requestId;
	global EinsteinPromptTemplateGenerationsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}