global class ExampleEntityRepresentation {
	global SObject customObject;
	global String exampleConnectUri;
	global String exampleId;
	global Integer exampleInteger;
	global Object exampleObject;
	global String exampleString;
	global ExampleEntityRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}