global class FindRoutesWithFewestSplitsUsingOCIItemInputRepresentation {
	global String locationGroupIdentifier;
	global List<String> ociExpandAttributes;
	global Double quantity;
	global String stockKeepingUnit;
	global FindRoutesWithFewestSplitsUsingOCIItemInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}