global class GetSlotStatusInput {
	global String channelId;
	global String endTime;
	global String externalFacilityId;
	global String externalPractitionerId;
	global String externalSlotId;
	global String resourceId;
	global String sourceSystem;
	global String startTime;
	global String territoryId;
	global String workTypeId;
	global GetSlotStatusInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}