global class IndividualCustomerLevelLimitInputRepresentation {
	global Integer financialLiabilityLimit;
	global Integer perCartLimit;
	global Integer perLineItemLimit;
	global Integer pointsPerCustomerLimit;
	global Integer usePerCustomerLimit;
	global Integer vouchersPerCustomerLimit;
	global IndividualCustomerLevelLimitInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}