global class ManagedContentChannel {
	global Long cacheControlMaxAge;
	global String channelId;
	global String channelName;
	global ConnectApi.ConnectManagedContentChannelType channelType;
	global String domain;
	global String domainId;
	global String domainName;
	global Boolean isChannelSearchable;
	global Boolean isDomainLocked;
	global Long mediaCacheControlMaxAge;
	global ManagedContentChannel() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}