global class PartyCreditProfileInput {
	global String creditBureauName;
	global String creditPrflReportIdentifier;
	global Integer creditScore;
	global Datetime creditScoreDate;
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global String partyProfileId;
	global String recordTypeId;
	global String referenceObjectId;
	global partyCreditProfileInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}