global class PromotionDetailsInputRepresentation {
	global Map<String,String> additionalFieldValues;
	global String description;
	global String displayName;
	global Datetime endDateTime;
	global String name;
	global String objective;
	global Integer priorityNumber;
	global String promotionCode;
	global Datetime startDateTime;
	global PromotionDetailsInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}