global class UnifiedPromotionsInputRepresentation {
	global ConnectApi.PromotionDetailsInputRepresentation promotionDetails;
	global ConnectApi.PromotionEligibilityInputRepresentation promotionEligibility;
	global ConnectApi.PromotionLimitInputRepresentation promotionLimits;
	global UnifiedPromotionsInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}