global class VisualforcePage {
	global Boolean showlabel;
	global Boolean showscrollbars;
	global String suggestedheight;
	global String suggestedwidth;
	global String url;
	global Integer getDisplayLines() { }
	global Boolean getShowLabel() { }
	global Boolean getShowScrollbars() { }
	global String getSuggestedHeight() { }
	global String getSuggestedWidth() { }
	global Integer getTabOrder() { }
	global String getType() { }
	global String getUrl() { }
	global String getValue() { }

}