global class DuplicateResult {
	global Boolean allowsave;
	global String duplicaterule;
	global String duplicateruleentitytype;
	global String errormessage;
	global List<Datacloud.MatchResult> matchresults;
	global String getDuplicateRule() { }
	global String getDuplicateRuleEntityType() { }
	global String getErrorMessage() { }
	global List<Datacloud.MatchResult> getMatchResults() { }
	global Boolean isAllowSave() { }

}